services:
  apache-php-composer:
    image: newdeveloper/apache-php-composer
    volumes:
      - ./html:/var/www/html/public
    ports:
      - "80:80"
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_TCP_PORT: 3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    